version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Jakarta"

  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    versioning-strategy: lockfile-only
    labels:
      - "dependencies"
    groups:
      dependencies:
        dependency-type: "production"
        patterns: ['*']
      dev-dependencies:
        dependency-type: "development"
        patterns: ['*']

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    versioning-strategy: lockfile-only
    labels:
      - "dependencies"
    groups:
      dependencies:
        dependency-type: "production"
        patterns: ['*']
      dev-dependencies:
        dependency-type: "development"
        patterns: ['*']
