name: Build

on:
  workflow_call:
    inputs:
      mode:
        description: 'Build environment mode'
        default: testing
        required: false
        type: string

jobs:
  frontend:
    runs-on: ubuntu-latest
    name: Frontend for ${{ inputs.mode }}

    environment:
      name: ${{ inputs.mode }}

    env:
      APP_ENV: ${{ vars.APP_ENV }}
      APP_URL: ${{ vars.APP_URL }}
      # COMPOSER_CACHE_DIR:

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, intl, libxml, mbstring, pcntl, ssh2, zip
          tools: composer:v2
          coverage: none

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18.x

      - name: Prepare environment
        id: composer-cache
        run: |
          git config user.name "Creasi.HQ" && git config user.email "dev@creasi.co"
          composer config -g github-oauth.github.com ${{ secrets.PAT }}
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Prepare Composer Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-8.1-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-8.1-composer-

      - name: Install PHP dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress --ansi
          composer ziggy:generate
          php artisan vendor:publish --tag creasi-assets --ansi

      - name: Build frontend
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: creasico
          SENTRY_PROJECT: creasi-skeleton
        run: |
          pnpm build --mode ${{ inputs.mode }}

      - name: Store assets
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: |
            public/build
            public/vendor
