name: Deploy
run-name: >-
  deploy ${{ github.ref_name }} to ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      target:
        description: Deployment target
        required: true
        type: environment
  workflow_run:
    workflows: [Code Quality]
    types: [completed]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    # uses: creasico/laravel-project/.github/workflows/prepare.yml@main
    uses: ./.github/workflows/prepare.yml
    secrets: inherit
    with:
      target: ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}
    needs: prepare

    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}
      url: ${{ vars.APP_URL }}

    env:
      APP_ENV: ${{ vars.APP_ENV }}
      APP_URL: ${{ vars.APP_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, intl, libxml, mbstring, pcntl, ssh2, zip
          tools: composer:v2
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ needs.prepare.outputs.composer-cache }}
          key: php-8.1-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-8.1-composer-

      - name: Download assets
        id: download
        uses: actions/download-artifact@v4
        with:
          name: build-${{ env.APP_ENV }}
          path: public

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --ansi

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.DEPLOY_SSH_RSAKEY }}
          ssh-config: ${{ secrets.DEPLOY_STAGING_CONFIG }}
          verbosity: ''
          dep: deploy -f scripts/deploy.php env=${{ env.APP_ENV }} --branch ${{ github.ref_name }}
