name: Deploy
run-name: >-
  deploy(${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}): ${{ github.ref_name }}
  with ${{ github.event_name == 'workflow_dispatch' && github.actor || github.event_name }}

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      target:
        description: Deployment target
        required: true
        type: environment
  workflow_run:
    workflows: [Code Quality]
    types: [completed]
    branches: [main]

env:
  APP_NAME: ${{ vars.APP_NAME }}
  APP_ENV: ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}
  APP_LOCALE: id

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    # uses: creasico/laravel-project/.github/workflows/build.yml@main
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      target: ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ github.env.APP_ENV }}
    needs: build

    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}
      url: ${{ vars.APP_URL }}

    env:
      APP_URL: ${{ vars.APP_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, intl, libxml, mbstring, pcntl, ssh2, zip
          tools: composer:v2
          coverage: none

      - name: Prepare environment
        id: composer-cache
        run: |
          git config user.name "Creasi.HQ" && git config user.email "dev@creasi.co"
          composer config -g github-oauth.github.com ${{ secrets.PAT }}
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-8.1-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-8.1-composer-

      - name: Download assets
        id: download
        uses: actions/download-artifact@v3
        with:
          name: public
          path: public

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --ansi

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.DEPLOY_SSH_RSAKEY }}
          ssh-config: ${{ secrets.DEPLOY_STAGING_CONFIG }}
          verbosity: ''
          dep: deploy -f scripts/deploy.php env=${{ env.APP_ENV }}
