name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]
  release:
    types: [created]

env:
  APP_NAME: Creasi App
  APP_ENV: testing
  # AWS_ENDPOINT: 'https://is3.cloudhost.id'
  # AWS_DEFAULT_REGION: 'ap-southeast-3'
  # AWS_BUCKET: creasi-staging
  MAIL_FROM_ADDRESS: devtest@creasi.co

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    env:
      MIX_SENTRY_LARAVEL_DSN: ${{ secrets.SENTRY_DSN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Build assets
        run: yarn build

      - name: Store assets
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: |
            public/css
            public/js
            public/mix-manifest.json

  tests:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    needs: build

    services:
      memcached:
        image: memcached:1.6-alpine
        ports:
          - 11211:11211
      postgresql:
        image: postgres:14
        env:
          POSTGRES_DB: creasico
          POSTGRES_USER: creasico
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1']
        stability: [prefer-lowest, prefer-stable]

    env:
      APP_KEY: ${{ secrets.APP_KEY }}
      BROWSERSTACK_BUILD: ${{ github.ref }}
      BROWSERSTACK_PROJECT: "${{ github.repository }} - ${{ github.workflow }}"
      DB_PASSWORD: secret
      SENTRY_TRACE_QUEUE_ENABLED: true

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql, gd, redis-phpredis/phpredis@5.3.5, igbinary, msgpack, lzf, zstd, lz4, memcached
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug
        env:
          REDIS_CONFIGURE_OPTS: --enable-redis --enable-redis-igbinary --enable-redis-msgpack --enable-redis-lzf --with-liblzf --enable-redis-zstd --with-libzstd --enable-redis-lz4 --with-liblz4
          REDIS_LIBS: liblz4-dev, liblzf-dev, libzstd-dev

      - name: Download assets
        id: download
        uses: actions/download-artifact@v3
        with:
          name: public
          path: public

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Run migrations
        run: php artisan migrate --seed

      - name: Run tests suite
        run: php artisan test
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          SENTRY_LARAVEL_DSN: ${{ secrets.SENTRY_DSN }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   needs: tests
  #   if: ${{ github.ref_name == 'develop' && github.event_name == 'push' }}

  #   environment:
  #     name: staging
  #     url: ${{ env.APP_URL }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Prepare
  #       run: |
  #         [[ ! -d $HOME/.ssh ]] && mkdir $HOME/.ssh
  #         echo "${{ secrets.STAGING_SERVER_RSAKEY }}" >> $HOME/.ssh/id_rsa
  #         echo "${{ secrets.STAGING_SERVER_SSH_HOSTS }}" >> $HOME/.ssh/known_hosts
  #         echo "${{ secrets.STAGING_SERVER_SSH_CONFIG }}" >> $HOME/.ssh/config
  #         chmod 600 $HOME/.ssh/* && ls -al $HOME/.ssh/
  #         git config user.name "Creasi.HQ" && git config user.email "dev@creasi.co"

  #     - name: Download assets
  #       id: download
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: public
  #         path: public

  #     - name: Deploy repo
  #       run: |
  #         git fetch creasico@creasi.co:~/git/wanho.git
  #         git push -fu creasico@creasi.co:~/git/wanho.git HEAD:master

  #     - name: Deploy assets
  #       run: rsync -zrtv public/ creasi.co:demo-wanho.creasi.co/public/
